#!/bin/sh
#
# git-gitignore-list
#
# Author: Vaidik Kapoor
# 
# git gitignore-list

echo "Available gitignores templates on Github:"
curl -s https://api.github.com/gitignore/templates | \
	sed -E 's/\"|,|\[|]//g'